# Generated by Django 4.2.16 on 2024-12-12 09:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('shares', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotto', models.CharField(max_length=3)),
                ('share', models.IntegerField()),
                ('status', models.CharField(default='รอการยืนยันการชำระเงิน', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.room')),
                ('round_bought', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Slip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prize', models.IntegerField()),
                ('status', models.CharField(default='กำลังดำเนินการ', max_length=255)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='app.room')),
                ('round_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to='app.round')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slips', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='LottoBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotto', models.CharField(max_length=6)),
                ('prize', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottos', to='app.room')),
                ('round_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottos', to='app.round')),
            ],
        ),
    ]
