# Generated by Django 4.2.17 on 2024-12-11 18:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank', models.CharField(blank=True, choices=[('bbl', 'Bangkok Bank'), ('kbank', 'Kasikorn Bank'), ('scb', 'Siam Commercial Bank'), ('ktb', 'Krung Thai Bank'), ('tmb', 'TMB Bank')], max_length=100, null=True)),
                ('banknumber', models.CharField(blank=True, max_length=10, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
