# Generated by Django 4.2.16 on 2024-12-10 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_transaction_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='room',
            field=models.IntegerField(default=0),
        ),
    ]
