# Generated by Django 4.2.17 on 2024-12-11 19:29

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_delete_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('banknumber', models.CharField(max_length=10, validators=[django.core.validators.MinLengthValidator(10), django.core.validators.MaxLengthValidator(10)])),
                ('bankname', models.TextField(choices=[('ธนาคารกรุงเทพ', 'Bangkok Bank'), ('ธนาคารกสิกรไทย', 'Kasikorn Bank'), ('ธนาคารไทยพาณิชย์', 'Siam Commercial Bank'), ('ธนาคารกรุงไทย', 'Krung Thai Bank'), ('ธนาคารทหารไทยธนชาต', 'TMBBank'), ('ธนาคารออมสิน', 'Government Savings Bank'), ('ยูโอบี ประเทศไทย', 'UOB Thailand'), ('ซิตี้แบงก์ ประเทศไทย', 'CitiBank Thailand')])),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
