# Generated by Django 4.2.16 on 2024-12-11 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_transaction_room'),
    ]

    operations = [
        migrations.RunSQL(
            sql="DROP TABLE IF EXISTS lotto.app_transaction;",
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_open', models.BooleanField(default=True)),
                ('shares', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotto', models.CharField(max_length=3)),
                ('share', models.IntegerField()),
                ('status', models.CharField(default='รอการยืนยันการชำระเงิน', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to=settings.AUTH_USER_MODEL)),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.room')),
                ('round_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='app.round')),
            ],
        ),
        migrations.CreateModel(
            name='LottoBought',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lotto', models.CharField(max_length=6)),
                ('prices', models.IntegerField()),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottos', to='app.room')),
                ('round_bought', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lottos', to='app.round')),
            ],
        ),
    ]
