# Generated by Django 4.2.17 on 2024-12-11 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_account'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='bankname',
            field=models.CharField(choices=[('ธนาคารกรุงเทพ', 'Bangkok Bank'), ('ธนาคารกสิกรไทย', 'Kasikorn Bank'), ('ธนาคารไทยพาณิชย์', 'Siam Commercial Bank'), ('ธนาคารกรุงไทย', 'Krung Thai Bank'), ('ธนาคารทหารไทยธนชาต', 'TMB Bank'), ('ธนาคารออมสิน', 'Government Savings Bank'), ('ยูโอบี ประเทศไทย', 'UOB Thailand'), ('ซิตี้แบงก์ ประเทศไทย', 'CitiBank Thailand')], max_length=50),
        ),
    ]
